import java.awt.geom.Path2D;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Class {@link SpecialRegionInfo} is used to store information (regionName, overrideLanguage)
 * about onebillion "special regions" -- refugee camps, etc. -- that may speak different languages
 * than the country default.
 */
public class SpecialRegionInfo
{
	String regionName;
	String overrideLanguage;
	private int layer;
	private Path2D.Double polygon;
	SpecialRegionInfo(String rn, int lay, String ol, Path2D.Double poly)
	{
		regionName = rn;
		layer = lay;
		overrideLanguage = ol;
		polygon = poly;
	}

	public static List<SpecialRegionInfo> specialRegions = new ArrayList<SpecialRegionInfo>();
	
	/* 
	 * The code in this static block is auto-generated by a custom tool that parses the KML data you get
	 * when you export KML from this map:
	 * 
	 * https://drive.google.com/open?id=1oFNef_5u61v5XSxIkxOVQ-YnFAsQKBZM&usp=sharing
	 *  
	 */
	static
	{
		Path2D.Double Dzaleka_Refugee_Camp = new Path2D.Double();
		Dzaleka_Refugee_Camp.moveTo(33.868103, -13.6603326);
		Dzaleka_Refugee_Camp.lineTo(33.8668156, -13.662772);
		Dzaleka_Refugee_Camp.lineTo(33.8660431, -13.6651907);
		Dzaleka_Refugee_Camp.lineTo(33.8664937, -13.6672132);
		Dzaleka_Refugee_Camp.lineTo(33.8706993, -13.6671507);
		Dzaleka_Refugee_Camp.closePath();
		specialRegions.add(new SpecialRegionInfo("Dzaleka Refugee Camp", 1, "Zambian English", Dzaleka_Refugee_Camp));

		Path2D.Double Tumbuka_Language_Area = new Path2D.Double();
		Tumbuka_Language_Area.moveTo(33.4643555, -10.856235);
		Tumbuka_Language_Area.lineTo(34.0507507, -11.4652202);
		Tumbuka_Language_Area.lineTo(34.2292786, -10.3986761);
		Tumbuka_Language_Area.lineTo(33.6600494, -10.4385202);
		Tumbuka_Language_Area.lineTo(33.7245941, -10.5080664);
		Tumbuka_Language_Area.lineTo(33.7067413, -10.60392);
		Tumbuka_Language_Area.closePath();
		specialRegions.add(new SpecialRegionInfo("Tumbuka Language Area", 1, "Tumbuka", Tumbuka_Language_Area));

		Path2D.Double Three_Chichewa_Villages = new Path2D.Double();
		Three_Chichewa_Villages.moveTo(33.7115596, -10.9479334);
		Three_Chichewa_Villages.lineTo(33.7280273, -11.0342118);
		Three_Chichewa_Villages.lineTo(33.9614868, -11.0827323);
		Three_Chichewa_Villages.lineTo(33.977978, -11.0018603);
		Three_Chichewa_Villages.closePath();
		specialRegions.add(new SpecialRegionInfo("Three Chichewa Villages", 2, "Chichewa", Three_Chichewa_Villages));
	}
	
	static Optional<SpecialRegionInfo> getSpecialRegionInfo(double lat, double lng)
	{
		Optional<SpecialRegionInfo> ret = Optional.empty();
		for (SpecialRegionInfo sri: SpecialRegionInfo.specialRegions)
		{
			if (sri.polygon.contains(lng, lat) && 
					(!ret.isPresent() || ret.get().layer < sri.layer))
				ret = Optional.of(sri);
		}
		return ret;
	}
}
